select
      cast(ps_unique_id as {{ dbt.type_string() }}) as ps_unique_id
    , cast(customer_nbr as {{ dbt.type_string() }}) as customer_nbr
    , cast(group_nbr as {{ dbt.type_string() }}) as group_nbr
    , cast(filler_1 as {{ dbt.type_string() }}) as filler_1
    , cast(subgroup_nbr as {{ dbt.type_string() }}) as subgroup_nbr
    , cast(account_nbr as {{ dbt.type_string() }}) as account_nbr
    , cast(file_id as {{ dbt.type_string() }}) as file_id
    , cast(clm_ln_type_cd as {{ dbt.type_string() }}) as clm_ln_type_cd
    , cast(non_prfrrd_srv_cd as {{ dbt.type_string() }}) as non_prfrrd_srv_cd
    , cast(plsp_prod_cd as {{ dbt.type_string() }}) as plsp_prod_cd
    , cast(product_ln_cd as {{ dbt.type_string() }}) as product_ln_cd
    , cast(classification_cd as {{ dbt.type_string() }}) as classification_cd
    , cast(bnft_pkg_id as {{ dbt.type_string() }}) as bnft_pkg_id
    , cast(plan_id as {{ dbt.type_string() }}) as plan_id
    , cast(benefit_tier as {{ dbt.type_string() }}) as benefit_tier
    , cast(fund_ctg_cd as {{ dbt.type_string() }}) as fund_ctg_cd
    , cast(src_subscriber_id as {{ dbt.type_string() }}) as src_subscriber_id
    , cast(subscriber_last_nm as {{ dbt.type_string() }}) as subscriber_last_nm
    , cast(subscriber_first_nm as {{ dbt.type_string() }}) as subscriber_first_nm
    , cast(subscriber_gender_cd as {{ dbt.type_string() }}) as subscriber_gender_cd
    , cast(subscriber_brth_dt as date) as subscriber_brth_dt
    , cast(subs_zip_cd as {{ dbt.type_string() }}) as subs_zip_cd
    , cast(subs_st_postal_cd as {{ dbt.type_string() }}) as subs_st_postal_cd
    , cast(coverage_type_cd as {{ dbt.type_string() }}) as coverage_type_cd
    , cast(subscriber_ssn_nbr as {{ dbt.type_string() }}) as subscriber_ssn_nbr
    , cast(member_id as {{ dbt.type_string() }}) as member_id
    , cast(member_number as {{ dbt.type_string() }}) as member_number
    , cast(member_last_nm as {{ dbt.type_string() }}) as member_last_nm
    , cast(member_first_nm as {{ dbt.type_string() }}) as member_first_nm
    , cast(mbr_gender_cd as {{ dbt.type_string() }}) as mbr_gender_cd
    , cast(mbr_rtp_type_cd as {{ dbt.type_string() }}) as mbr_rtp_type_cd
    , cast(member_birth_dt as date) as member_birth_dt
    , cast(src_clm_id as {{ dbt.type_string() }}) as src_clm_id
    , cast(acas_gen_seq_nbr as {{ dbt.type_string() }}) as acas_gen_seq_nbr
    , cast(prev_clm_seg_id as {{ dbt.type_string() }}) as prev_clm_seg_id
    , cast(derived_tcn_nbr as {{ dbt.type_string() }}) as derived_tcn_nbr
    , cast(src_claim_line_id as {{ dbt.type_string() }}) as src_claim_line_id
    , cast(claim_line_id as {{ dbt.type_string() }}) as claim_line_id
    , cast(ntwk_srv_area_id as {{ dbt.type_string() }}) as ntwk_srv_area_id
    , cast(paid_prvdr_nsa_id as {{ dbt.type_string() }}) as paid_prvdr_nsa_id
    , cast(srv_capacity_cd as {{ dbt.type_string() }}) as srv_capacity_cd
    , cast(pcp_tax_id_format_cd as {{ dbt.type_string() }}) as pcp_tax_id_format_cd
    , cast(pcp_tax_id_nbr as {{ dbt.type_string() }}) as pcp_tax_id_nbr
    , cast(pcp_nm as {{ dbt.type_string() }}) as pcp_nm
    , cast(srv_prvdr_tax_id_format_cd as {{ dbt.type_string() }}) as srv_prvdr_tax_id_format_cd
    , cast(srv_prvdr_tax_id_nbr as {{ dbt.type_string() }}) as srv_prvdr_tax_id_nbr
    , cast(srv_prvdr_id as {{ dbt.type_string() }}) as srv_prvdr_id
    , cast(srv_prvdr_nm as {{ dbt.type_string() }}) as srv_prvdr_nm
    , cast(srv_prvdr_address_line_1_txt as {{ dbt.type_string() }}) as srv_prvdr_address_line_1_txt
    , cast(srv_prvdr_address_line_2_txt as {{ dbt.type_string() }}) as srv_prvdr_address_line_2_txt
    , cast(srv_prvdr_city_nm as {{ dbt.type_string() }}) as srv_prvdr_city_nm
    , cast(srv_prvdr_state_postal_cd as {{ dbt.type_string() }}) as srv_prvdr_state_postal_cd
    , cast(srv_prvdr_zip_cd as {{ dbt.type_string() }}) as srv_prvdr_zip_cd
    , cast(srv_prvdr_provider_type_cd as {{ dbt.type_string() }}) as srv_prvdr_provider_type_cd
    , cast(srv_prvdr_specialty_cd as {{ dbt.type_string() }}) as srv_prvdr_specialty_cd
    , cast(payee_cd as {{ dbt.type_string() }}) as payee_cd
    , cast(paid_prvdr_par_cd as {{ dbt.type_string() }}) as paid_prvdr_par_cd
    , cast(received_dt as date) as received_dt
    , cast(adjn_dt as date) as adjn_dt
    , cast(srv_start_dt as date) as srv_start_dt
    , cast(srv_stop_dt as date) as srv_stop_dt
    , cast(date_processed as date) as date_processed
    , cast(filler_2 as {{ dbt.type_string() }}) as filler_2
    , cast(filler_3 as {{ dbt.type_string() }}) as filler_3
    , cast(filler_4 as {{ dbt.type_string() }}) as filler_4
    , cast(mdc_cd as {{ dbt.type_string() }}) as mdc_cd
    , cast(drg_cd as {{ dbt.type_string() }}) as drg_cd
    , cast(prcdr_cd as {{ dbt.type_string() }}) as prcdr_cd
    , cast(prcdr_modifier_cd as {{ dbt.type_string() }}) as prcdr_modifier_cd
    , cast(prcdr_type_cd as {{ dbt.type_string() }}) as prcdr_type_cd
    , cast(filler_5 as {{ dbt.type_string() }}) as filler_5
    , cast(filler_6 as {{ dbt.type_string() }}) as filler_6
    , cast(filler_7 as {{ dbt.type_string() }}) as filler_7
    , cast(type_srv_cd as {{ dbt.type_string() }}) as type_srv_cd
    , cast(benefit_cd as {{ dbt.type_string() }}) as benefit_cd
    , cast(tooth_1_nbr as {{ dbt.type_string() }}) as tooth_1_nbr
    , cast(plc_srv_cd as {{ dbt.type_string() }}) as plc_srv_cd
    , cast(dschrg_status_cd as {{ dbt.type_string() }}) as dschrg_status_cd
    , cast(revenue_cd as {{ dbt.type_string() }}) as revenue_cd
    , cast(hcfa_bill_type_cd as {{ dbt.type_string() }}) as hcfa_bill_type_cd
    , cast(unit_cnt as {{ dbt.type_numeric() }}) as unit_cnt
    , cast(src_unit_cnt as {{ dbt.type_numeric() }}) as src_unit_cnt
    , cast(src_billed_amt as {{ dbt.type_numeric() }}) as src_billed_amt
    , cast(billed_amt as {{ dbt.type_numeric() }}) as billed_amt
    , cast(not_covered_amt_1 as {{ dbt.type_numeric() }}) as not_covered_amt_1
    , cast(not_covered_amt_2 as {{ dbt.type_numeric() }}) as not_covered_amt_2
    , cast(not_covered_amt_3 as {{ dbt.type_numeric() }}) as not_covered_amt_3
    , cast(clm_ln_msg_cd_1 as {{ dbt.type_string() }}) as clm_ln_msg_cd_1
    , cast(clm_ln_msg_cd_2 as {{ dbt.type_string() }}) as clm_ln_msg_cd_2
    , cast(clm_ln_msg_cd_3 as {{ dbt.type_string() }}) as clm_ln_msg_cd_3
    , cast(covered_amt as {{ dbt.type_numeric() }}) as covered_amt
    , cast(allowed_amt as {{ dbt.type_numeric() }}) as allowed_amt
    , cast(filler_8 as {{ dbt.type_string() }}) as filler_8
    , cast(srv_copay_amt as {{ dbt.type_numeric() }}) as srv_copay_amt
    , cast(src_srv_copay_amt as {{ dbt.type_numeric() }}) as src_srv_copay_amt
    , cast(deductible_amt as {{ dbt.type_numeric() }}) as deductible_amt
    , cast(coinsurance_amt as {{ dbt.type_numeric() }}) as coinsurance_amt
    , cast(src_coins_amt as {{ dbt.type_numeric() }}) as src_coins_amt
    , cast(bnft_payable_amt as {{ dbt.type_numeric() }}) as bnft_payable_amt
    , cast(paid_amt as {{ dbt.type_numeric() }}) as paid_amt
    , cast(cob_paid_amt as {{ dbt.type_numeric() }}) as cob_paid_amt
    , cast(ahf_bfd_amt as {{ dbt.type_numeric() }}) as ahf_bfd_amt
    , cast(ahf_paid_amt as {{ dbt.type_numeric() }}) as ahf_paid_amt
    , cast(negot_savings_amt as {{ dbt.type_numeric() }}) as negot_savings_amt
    , cast(r_c_savings_amt as {{ dbt.type_numeric() }}) as r_c_savings_amt
    , cast(cob_savings_amt as {{ dbt.type_numeric() }}) as cob_savings_amt
    , cast(src_cob_svngs_amt as {{ dbt.type_numeric() }}) as src_cob_svngs_amt
    , cast(pri_payer_cvg_cd as {{ dbt.type_string() }}) as pri_payer_cvg_cd
    , cast(cob_type_cd as {{ dbt.type_string() }}) as cob_type_cd
    , cast(cob_cd as {{ dbt.type_string() }}) as cob_cd
    , cast(prcdr_cd_ndc as {{ dbt.type_string() }}) as prcdr_cd_ndc
    , cast(src_clm_mbr_id as {{ dbt.type_string() }}) as src_clm_mbr_id
    , cast(clm_ln_status_cd as {{ dbt.type_string() }}) as clm_ln_status_cd
    , cast(src_member_id as {{ dbt.type_string() }}) as src_member_id
    , cast(reversal_cd as {{ dbt.type_string() }}) as reversal_cd
    , cast(admit_cnt as {{ dbt.type_string() }}) as admit_cnt
    , cast(admin_savings_amt as {{ dbt.type_numeric() }}) as admin_savings_amt
    , cast(adj_prvdr_dsgnn_cd as {{ dbt.type_string() }}) as adj_prvdr_dsgnn_cd
    , cast(aex_plan_dsgntn_cd as {{ dbt.type_string() }}) as aex_plan_dsgntn_cd
    , cast(benefit_tier_cd as {{ dbt.type_string() }}) as benefit_tier_cd
    , cast(aex_prvdr_spctg_cd as {{ dbt.type_string() }}) as aex_prvdr_spctg_cd
    , cast(prod_distnctn_cd as {{ dbt.type_string() }}) as prod_distnctn_cd
    , cast(billed_eligible_amt as {{ dbt.type_numeric() }}) as billed_eligible_amt
    , cast(srv_provider_class_cd as {{ dbt.type_string() }}) as srv_provider_class_cd
    , cast(poa_cd_1 as {{ dbt.type_string() }}) as poa_cd_1
    , cast(poa_cd_2 as {{ dbt.type_string() }}) as poa_cd_2
    , cast(poa_cd_3 as {{ dbt.type_string() }}) as poa_cd_3
    , cast(filler_9 as {{ dbt.type_string() }}) as filler_9
    , cast(filler_10 as {{ dbt.type_string() }}) as filler_10
    , cast(filler_11 as {{ dbt.type_string() }}) as filler_11
    , cast(pricing_mthd_cd as {{ dbt.type_string() }}) as pricing_mthd_cd
    , cast(type_class_cd as {{ dbt.type_string() }}) as type_class_cd
    , cast(specialty_ctg_cd as {{ dbt.type_string() }}) as specialty_ctg_cd
    , cast(srv_prvdr_npi as {{ dbt.type_string() }}) as srv_prvdr_npi
    , cast(ttl_ded_met_ind as {{ dbt.type_string() }}) as ttl_ded_met_ind
    , cast(ttl_interest_amt as {{ dbt.type_numeric() }}) as ttl_interest_amt
    , cast(ttl_surcharge_amt as {{ dbt.type_numeric() }}) as ttl_surcharge_amt
    , cast(filler_12 as {{ dbt.type_string() }}) as filler_12
    , cast(hcfa_plc_srv_cd as {{ dbt.type_string() }}) as hcfa_plc_srv_cd
    , cast(hcfa_admit_src_cd as {{ dbt.type_string() }}) as hcfa_admit_src_cd
    , cast(hcfa_admit_type_cd as {{ dbt.type_string() }}) as hcfa_admit_type_cd
    , cast(src_admit_dt as date) as src_admit_dt
    , cast(src_discharge_dt as date) as src_discharge_dt
    , cast(prcdr_modifier_cd_2 as {{ dbt.type_string() }}) as prcdr_modifier_cd_2
    , cast(prcdr_modifier_cd_3 as {{ dbt.type_string() }}) as prcdr_modifier_cd_3
    , cast(poa_cd_4 as {{ dbt.type_string() }}) as poa_cd_4
    , cast(poa_cd_5 as {{ dbt.type_string() }}) as poa_cd_5
    , cast(poa_cd_6 as {{ dbt.type_string() }}) as poa_cd_6
    , cast(poa_cd_7 as {{ dbt.type_string() }}) as poa_cd_7
    , cast(poa_cd_8 as {{ dbt.type_string() }}) as poa_cd_8
    , cast(poa_cd_9 as {{ dbt.type_string() }}) as poa_cd_9
    , cast(poa_cd_10 as {{ dbt.type_string() }}) as poa_cd_10
    , cast(pri_icd9_dx_cd as {{ dbt.type_string() }}) as pri_icd9_dx_cd
    , cast(icd9_dx_cd_2 as {{ dbt.type_string() }}) as icd9_dx_cd_2
    , cast(icd9_dx_cd_3 as {{ dbt.type_string() }}) as icd9_dx_cd_3
    , cast(icd9_dx_cd_4 as {{ dbt.type_string() }}) as icd9_dx_cd_4
    , cast(icd9_dx_cd_5 as {{ dbt.type_string() }}) as icd9_dx_cd_5
    , cast(icd9_dx_cd_6 as {{ dbt.type_string() }}) as icd9_dx_cd_6
    , cast(icd9_dx_cd_7 as {{ dbt.type_string() }}) as icd9_dx_cd_7
    , cast(icd9_dx_cd_8 as {{ dbt.type_string() }}) as icd9_dx_cd_8
    , cast(icd9_dx_cd_9 as {{ dbt.type_string() }}) as icd9_dx_cd_9
    , cast(icd9_dx_cd_10 as {{ dbt.type_string() }}) as icd9_dx_cd_10
    , cast(icd9_prcdr_cd_1 as {{ dbt.type_string() }}) as icd9_prcdr_cd_1
    , cast(icd9_prcdr_cd_2 as {{ dbt.type_string() }}) as icd9_prcdr_cd_2
    , cast(icd9_prcdr_cd_3 as {{ dbt.type_string() }}) as icd9_prcdr_cd_3
    , cast(icd9_prcdr_cd_4 as {{ dbt.type_string() }}) as icd9_prcdr_cd_4
    , cast(icd9_prcdr_cd_5 as {{ dbt.type_string() }}) as icd9_prcdr_cd_5
    , cast(icd9_prcdr_cd_6 as {{ dbt.type_string() }}) as icd9_prcdr_cd_6
    , cast(ahf_det_order_cd as {{ dbt.type_string() }}) as ahf_det_order_cd
    , cast(ahf_mbr_coins_amt as {{ dbt.type_numeric() }}) as ahf_mbr_coins_amt
    , cast(ahf_mbr_copay_amt as {{ dbt.type_numeric() }}) as ahf_mbr_copay_amt
    , cast(ahf_mbr_ded_amt as {{ dbt.type_numeric() }}) as ahf_mbr_ded_amt
    , cast(filler_13 as {{ dbt.type_string() }}) as filler_13
    , cast(filler_14 as {{ dbt.type_string() }}) as filler_14
    , cast(icd_10_ind as {{ dbt.type_string() }}) as icd_10_ind
    , cast(xchng_id as {{ dbt.type_string() }}) as xchng_id
    , cast(filler_15 as {{ dbt.type_string() }}) as filler_15
from {{ source('aetna', 'aetna_medical_claims_raw') }}
